### ISSUE TITLE
[Backend] [COVID-19]

### ISSUE THREAD

**Issue by taimurkashif** [bitprj/mdx-deck#4]
DRY RUN ON FRIDAY 4/24 6PM PST
- [ ] Week 1 Tasks ( Issue #2 ) 
     - [ ] "First Draft" deadline - 4/10/20
     - [ ] "Final Draft" deadline - 4/12/20
- [ ] Week 2 Tasks ( Issue #6 )
     - [ ] "First Draft" deadline - 4/17/20
     - [ ] "Final Draft" deadline - 4/19/20
- [ ] Week 3 Tasks ( Issue #8 )
     - [ ] "First Draft" deadline - 4/24/20
     - [ ] "Final Draft" deadline - 4/26/20
